language: android

jdk: oraclejdk8

before_install:
  - cd MainApplication

android:
  components:

    #Tools
    - tools
    - platform-tools
    - build-tools-24.0.3

    # SDK version
    - android-24
    
    #Extras
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support

    #Emulators
    - sys-img-armeabi-v7a-android-24
        
    # Other stuff can be added here, see travis-ci.org for details

  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gd-license-.+
