language: android

jdk: oraclejdk8

android:
  components:

    #Tools
    - tools
    - platform-tools
    - build-tools-25.0.2

    # SDK version
    - android-25
    
    #Extras
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support

    #Emulators
    - sys-img-armeabi-v7a-android-25
        
    # Other stuff can be added here, see travis-ci.org for details

  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gd-license-.+

before_install:
  - cd MainApplication

install:
  - echo y | android update sdk -u -a -t tools
  - echo y | android update sdk -u -a -t platform-tools
  - echo y | android update sdk -u -a -t build-tools-25.0.2
  - echo y | android update sdk -u -a -t android-25
  - echo y | android update sdk -u -a -t extra-google-m2repository
  - echo y | android update sdk -u -a -t extra-android-m2repository
  - echo y | android update sdk -u -a -t extra-android-support
