language: android

jdk: oraclejdk8

before_install:
  - cd MainApplication

android:
  components:

    # SDK version
    - android-23
    - build-tools-23.0.3

    #Tools
    - tools
    - platform-tools

    #Emulators
    - sys-img-armeabi-v7a-android-24
        
    # Other stuff can be added here, see travis-ci.org for details
